name: README with Office Quote

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-office-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Get Quote and Update README
        run: node .
      - name: Add README to Stage
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "aaishikasb"
          git config --global user.email "mail.aaishika@gmail.com"
          git commit -m "[Automated] feat: Update Quote"
      - name: Push Updated README
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
